select * from carprice limit 10;
select * from carprice order by car_ID desc limit 10;
select distinct(carbody) from carprice;
select * from carprice order by price limit 5;
select * from carprice order by price desc limit 5;
select carbody,count(carbody) from carprice group by carbody;
select carbody,count(carbody) from carprice group by carbody order by count(carbody) desc;
select carbody,count(carbody) from carprice group by carbody having count(carbody)>=15 order by count(carbody) desc;
select carbody,fueltype,count(car_ID) from carprice group by carbody,fueltype;
select fueltype,avg(price) from carprice group by fueltype;
select carbody,avg(price) from carprice group by carbody;
select fueltype,avg(price) from carprice group by fueltype order by avg(price) desc limit 1;
alter table carprice add avgmil float;
update carprice set avgmil = (citympg+highwaympg)/2;
select carbody,avg(carlength) from carprice where carbody = "sedan";
select carbody,avg(price) from carprice group by carbody;
select fueltype,max(citympg) as CITYMPG,max(highwaympg) as HIGHWAYMPG from carprice group by fueltype;
select * from carprice where carName like "a%";
select * from carprice where carName like "%a";
select * from carprice where carName like "n_s%e";
select carbody, count(carbody) from carprice where carbody = "sedan";
